spring.application.name=SpringBootDataJPA

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database (Postgres) Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hms_db?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=root

# Dummy Data
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:postgresData.sql